eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
              defaultZone: http://localhost:8888/eureka/
  instance:
    preferIpAddress: true
management:
  endpoint:
       routes:
         enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
server:
    port: 8080
spring:
  application:
    name: gateway